### ISSUE TITLE
Design new screens for kownsl (submit approval/provide advice)

### ISSUE THREAD

**Issue by kelvincy** [GemeenteUtrecht/zaakafhandelcomponent#123]
New designs for kownsl that are currently not in the ZAC

**Comment by kelvincy** [comment]
@damm89 @sergei-maertens 

The designs for the external kownsl screens. Could you guys have a look at it and give some feedback?

![Advies](https://user-images.githubusercontent.com/14090502/99234174-7bf3a280-27f4-11eb-9092-8b32e6835b43.png)
![Akkoord](https://user-images.githubusercontent.com/14090502/99234180-7d24cf80-27f4-11eb-8ae3-421959881bc3.png)

**Comment by damm89** [comment]
Ziet er goed uit!

**Comment by sergei-maertens** [comment]
- "Eigenschappen" sounds confusing in the sense that eigenschappen is its own concept for a Zaak. It's a pre-defined set of properties that can be used, next to the static properties that are part of a Zaak resource (see https://zaken-api.vng.cloud/api/v1/schema/#operation/zaak_read)

- the document uploads for advice relate directly back to a particular document that's related to the zaak - it's meant to edit that document (add annotations, reword things etc.) and then upload those "suggestions". In the design I don't see that relation. What effectively happens on upload, is that a new version of the source document is created

**Comment by damm89** [comment]
I like the design! Nice and clear.

We're missing the conditional section on previous "toelichtingen" & "adviezen" in both designs.

**Comment by kelvincy** [comment]
Checked naming and functionality in the design with Functioneel Beheer. See updated designs down below. The updated designs are currently being reviewed by the UX team. 

![Advies3](https://user-images.githubusercontent.com/14090502/99525612-57d1c600-299a-11eb-8d3c-2203fca90896.png)
![Akkoord3](https://user-images.githubusercontent.com/14090502/99525616-599b8980-299a-11eb-8fa7-075763ece891.png)
