### ISSUE TITLE
Protect data in the UserViewSet better

### ISSUE THREAD

**Issue by sergei-maertens** [GemeenteUtrecht/zaakafhandelcomponent#195]
I was just looking at the UserViewSet in the accounts because of a remark from Kelvin, and I think we should pro-actively do something to prevent data-exfiltration. Because of the SSO, as soon as you can log in to the ZAC, you can hit that endpoint and essentially get the list of all Utrecht staff accounts that have ever logged in.

If someone does that, I think it should:
* be logged
* possibly explicitly assign a user permission accounts:can-view-users

The endpoint exists for auto-complete purposes & for BPTL reading out some data from the ZAC for the process model. If we log it, we can audit it. If we assign user permissions, we prevent abuse - this would mean that only people that actively have to use the ZAC can hit that endpoint, rather than every single person with a Utrecht account

**Acceptance criteria**

- [ ] `GET` requests to list/retrieve are logged (django-timeline-logger? we want persistent logging, not logs that dissapear because of the infrastructure configuration)
- [ ] Add explicit permission and connect it to the permissions/authorizations machinery

**Comment by CMasselink** [comment]
> we prevent abuse - this would mean that only people that actively have to use the ZAC can hit that endpoint, rather than every single person with a Utrecht account

Shouldn't this be the basic principle for all access related questions? Users should only be able to use the application functions they need to do their job, nothing more (a bit depending on information classification).
If I don't have permissions to use the application, I shouldn't be able to use functions / endpoints of that application, regardless if SSO is implemented. 

Is this a consequence of not implementing specific claims/scopes in SSO for this application?

**Comment by sergei-maertens** [comment]
> Shouldn't this be the basic principle for all access related questions? Users should only be able to use the application functions they need to do their job, nothing more (a bit depending on information classification).

yes, we have those locked down now with data-specific permissions: https://github.com/GemeenteUtrecht/zaakafhandelcomponent/blob/main/backend/src/zac/core/permissions.py

> Is this a consequence of not implementing specific claims/scopes in SSO for this application?

Indirectly, yes. You could limit this that users need a particular ADFS group before they're allowed to log in, and then a `LoginRequired` permission is sufficient. However, the fact that users can log in to the application now means that we need more fine-grained permissions on what is otherwise sufficiently protected by requiring login.

**Comment by CMasselink** [comment]
I assume the auto-compleet function is used for things like assigning cases to a certain employee? I think auto-complete should only return names of employees who still have an active account and appropriate permissions in the application.

I think it is best to discuss with the DISO and security team if it is considered a problem if a user can view active users of an application by using a search endpoint. All employees have acccess to the Outlook Address book and can view all employees of the gemeente Utrecht.....
