### ISSUE TITLE
Get and set the result of a case

### ISSUE THREAD

**Issue by damm89** [GemeenteUtrecht/zaakafhandelcomponent#253]
Currently it seems like there is no way to set the result of a case. The old UI has blocked off the "Zaak afhandelen" button and there is no endpoint (/usertask implementation) yet to set this from the new frontend.

To do:

- [ ] add case handling serializer to serializer mapping of SubmitUserTaskSerializer

**Comment by sergei-maertens** [comment]
This is done using BPTL and a user task in the process to select an option (using the generic form). The value of that form field is mapped to a resultaattype in the proces model.

The old UI blocks this off _if and only if_ there is no active Camunda process for that case.
