### ISSUE TITLE
Update authorization for ZaakDocuments endpoint

### ISSUE THREAD

**Issue by annashamray** [GemeenteUtrecht/zaakafhandelcomponent#295]
ZaakDocuments endpoint uses permissions both for zaken and for  documenten
Now it checks zaak permissions as usual (using `CanReadOrUpdateZaken` ) and after it filters documents based on document permissions with `filter_documenten_for_permissions` function. The function `filter_documenten_for_permissions` uses the old `PermissionsBackend` which is deprecated and should be removed. 

Todo:
* [x] remove the usage of `PermissionsBackend` from BFF endpoints
* [x] put as much code as possible to permissions to check documents.

**Comment by damm89** [comment]
agree
