### ISSUE TITLE
Bug kownsl user tasks

### ISSUE THREAD

**Issue by damm89** [GemeenteUtrecht/zaakafhandelcomponent#306]
After configuring adviseren/accordering the users' permissions are checked by their presence in the user_deadlines field once you execute the user task. If you appoint a different assignee/delegate on the zac-detail page, they will not pass permission checks as the new user might not be in the user_deadlines field.

**Comment by annashamray** [comment]
In the backend it was fixed when atomic permission handlers were updated here - https://github.com/GemeenteUtrecht/zaakafhandelcomponent/pull/386

But while testing it I've noticed the FE bug in the werkvooraad  - if the user doesn't have permissions for `/api/workstack/access-requests` (i.e. the request to this endpoint returns 403) then other werkvooraad panels don't show anything even if the user can have tasks or activities.
