### ISSUE TITLE
Extend the users viewset to look up a user by e-mail address

### ISSUE THREAD

**Issue by sergei-maertens** [GemeenteUtrecht/zaakafhandelcomponent#342]
... and retrieve the username (can be existing serializer which has username and e-mail address).

Currently the filters support lookups via username (and ID?). There are processes where the e-mail address of a user is entered in the form, and in the BPM process this will be looked up to get the username so that the username can be related to the zaak (as "behandelaar"). This will result in the case showing up in the workstack, which it doesn't if you relate just via e-mail address.

**Comment by sergei-maertens** [comment]
Relates to https://github.com/GemeenteUtrecht/ZGW/issues/789

**Comment by damm89** [comment]
https://github.com/GemeenteUtrecht/zaakafhandelcomponent/pull/367
