### ISSUE TITLE
Clean up old UI code

### ISSUE THREAD

**Issue by sergei-maertens** [GemeenteUtrecht/zaakafhandelcomponent#360]
The ZAC started out with Django templates with sprinkles of React here and there, most of which can be deleted.

## The following should NOT be deleted yet

* Login page (new UI currently redirects to old login page): https://github.com/GemeenteUtrecht/zaakafhandelcomponent/blob/main/backend/src/zac/accounts/views.py#L4
* Executing camunda user tasks of the type `zac:doRedirect`, which involves two Django views - one task routing and the actual redirect task view:
    * https://github.com/GemeenteUtrecht/zaakafhandelcomponent/blob/main/backend/src/zac/core/views/processes.py#L152
    * https://github.com/GemeenteUtrecht/zaakafhandelcomponent/blob/main/backend/src/zac/core/views/processes.py#L166
    * https://github.com/GemeenteUtrecht/zaakafhandelcomponent/blob/main/backend/src/zac/core/views/processes.py#L279
* Zaakbesluiten overview is not ported yet to new UI: https://github.com/GemeenteUtrecht/zaakafhandelcomponent/blob/main/backend/src/zac/core/views/besluiten.py
* Download documents - not sure if new UI does this too https://github.com/GemeenteUtrecht/zaakafhandelcomponent/blob/main/backend/src/zac/core/views/documents.py
  if it does, it can be deleted

## Old UI safe to delete

* Validsign:
    * https://github.com/GemeenteUtrecht/zaakafhandelcomponent/blob/main/backend/src/zac/contrib/validsign/templates/validsign/configure_package.html
* Core
    * all zaken views: https://github.com/GemeenteUtrecht/zaakafhandelcomponent/blob/main/backend/src/zac/core/views/zaken.py
    * cache flushing is probably not used by anyone anymore: https://github.com/GemeenteUtrecht/zaakafhandelcomponent/blob/main/backend/src/zac/core/views/cache.py
    * camunda: https://github.com/GemeenteUtrecht/zaakafhandelcomponent/blob/main/backend/src/zac/core/views/processes.py
      delete `SendMessage`, `ClaimTaskView`
    * search: not used anymore and we need to migrate it to new UI anyway https://github.com/GemeenteUtrecht/zaakafhandelcomponent/blob/main/backend/src/zac/core/views/search.py
* Forms: https://github.com/GemeenteUtrecht/zaakafhandelcomponent/blob/main/backend/src/zac/forms/views.py
* js: 
    * https://github.com/GemeenteUtrecht/zaakafhandelcomponent/tree/main/backend/src/zac/js/components/bag-object-selection -> needs to be redone anyway
    * https://github.com/GemeenteUtrecht/zaakafhandelcomponent/tree/main/backend/src/zac/js/components/betrokkenen
    * https://github.com/GemeenteUtrecht/zaakafhandelcomponent/tree/main/backend/src/zac/js/components/case-activities -> not sure if we have the activities in the new UI already?
    * https://github.com/GemeenteUtrecht/zaakafhandelcomponent/tree/main/backend/src/zac/js/components/checkbox-select-dynamic
    * https://github.com/GemeenteUtrecht/zaakafhandelcomponent/tree/main/backend/src/zac/js/components/documents
    * https://github.com/GemeenteUtrecht/zaakafhandelcomponent/tree/main/backend/src/zac/js/components/informatieobjecttype-forms
    * https://github.com/GemeenteUtrecht/zaakafhandelcomponent/tree/main/backend/src/zac/js/components/processes
    * https://github.com/GemeenteUtrecht/zaakafhandelcomponent/tree/main/backend/src/zac/js/components/review-requests
    * https://github.com/GemeenteUtrecht/zaakafhandelcomponent/tree/main/backend/src/zac/js/components/review-user-select
    * https://github.com/GemeenteUtrecht/zaakafhandelcomponent/tree/main/backend/src/zac/js/components/timeline -> related to case-activities, so double check
    * https://github.com/GemeenteUtrecht/zaakafhandelcomponent/tree/main/backend/src/zac/js/components/user-selection
    * https://github.com/GemeenteUtrecht/zaakafhandelcomponent/tree/main/backend/src/zac/js/components/validSign
    * https://github.com/GemeenteUtrecht/zaakafhandelcomponent/blob/main/backend/src/zac/js/components/Tabs.js I think
    * https://github.com/GemeenteUtrecht/zaakafhandelcomponent/blob/main/backend/src/zac/js/components/ZaaktypeSelect.js
    * https://github.com/GemeenteUtrecht/zaakafhandelcomponent/blob/main/backend/src/zac/js/components/links.js
    * https://github.com/GemeenteUtrecht/zaakafhandelcomponent/blob/main/backend/src/zac/js/components/tab.js
    * https://github.com/GemeenteUtrecht/zaakafhandelcomponent/blob/main/backend/src/zac/js/utils/async-load.js
    * https://github.com/GemeenteUtrecht/zaakafhandelcomponent/tree/main/backend/src/zac/js/views/search
    * https://github.com/GemeenteUtrecht/zaakafhandelcomponent/tree/main/backend/src/zac/js/views/zaak-detail
    * https://github.com/GemeenteUtrecht/zaakafhandelcomponent/tree/main/backend/src/zac/js/views/zaak-list
    * https://github.com/GemeenteUtrecht/zaakafhandelcomponent/tree/main/backend/src/zac/regiezaken
    * https://github.com/GemeenteUtrecht/zaakafhandelcomponent/blob/main/backend/src/zac/reports/views.py
* sass
    * https://github.com/GemeenteUtrecht/zaakafhandelcomponent/tree/main/backend/src/zac/sass/views
    * https://github.com/GemeenteUtrecht/zaakafhandelcomponent/tree/main/backend/src/zac/sass/ds not sure if this is still used anywhere, I think it's relevant for the login page
    * https://github.com/GemeenteUtrecht/zaakafhandelcomponent/tree/main/backend/src/zac/sass/components/contrib
    * https://github.com/GemeenteUtrecht/zaakafhandelcomponent/tree/main/backend/src/zac/sass/components/tables
    * https://github.com/GemeenteUtrecht/zaakafhandelcomponent/blob/main/backend/src/zac/sass/components/ except for the `_body.scss` I think
* https://github.com/GemeenteUtrecht/zaakafhandelcomponent/tree/main/backend/src/zac/templatetags
* werkvoorraad: https://github.com/GemeenteUtrecht/zaakafhandelcomponent/blob/main/backend/src/zac/werkvoorraad/views.py

That should cover it, mostly.

Of course, when deleting views, it's expected that also the matching URL route is deleted and the templates used by the view.

**Comment by annashamray** [comment]
Also when you hijack the user you are redirecting to the old UI. 
Functional managers use hijacking actively, so it should also be redirected to the new UI
