### ISSUE TITLE
een adviseur kan een document wat door een eerdere adviseur is aangepast niet meer openen (duister probleem)

### ISSUE THREAD

**Issue by JurjenBert** [GemeenteUtrecht/zaakafhandelcomponent#412]

**Comment by damm89** [comment]
Problem: authentication problems with the Alfresco DRC.
Context: in the zac there is a function that loops through all available DRCs to find a document.
(Temporary?) Solution: in the admin of zac-test removed the Alfresco DRC as a DRC service and set it to ORC (overige...).

Please confirm that it works as expected now.
