### ISSUE TITLE
[bug] Object search seems to be broken.

### ISSUE THREAD

**Issue by svenvandescheur** [GemeenteUtrecht/zaakafhandelcomponent#436]
500 error are returned from backend when attempting to search for objects (and selecting them). At the time of writing reproducable at:

https://zac-test.utrechtproeftuin.nl/ui/zoeken

1. Go to https://zac-test.utrechtproeftuin.nl/ and log in.
2. Navigate to "Zoeken".
3. Select tab "Zoeken op zaakobject".
4. Select a "Gebied" for example "Provincie: Utrecht".
5. Click "Zoeken".
6. Select a result, for example "Adres: Utrechtsestraat 42, Type: Laadpaal"
7. An error occurs. See you browsers' developer tools for more information.

**Comment by sergei-maertens** [comment]
Fixed after re-indexing ES on the server
