### ISSUE TITLE
:bug: Wrong endpoint is called when updating zaakdocumentvertrouwelijkheidaanduiding

### ISSUE THREAD

**Issue by damm89** [GemeenteUtrecht/zaakafhandelcomponent#491]
When updating zaakdocumentvertrouwelijkheidaanduiding (see image), 
![image](https://user-images.githubusercontent.com/52245527/141083299-5099b17f-cd7b-4e9f-b9b7-778891b66776.png)

the wrong endpoint is called (see image).
![image](https://user-images.githubusercontent.com/52245527/141083101-05d53b32-dd49-4fa0-a4aa-a55eece3cae8.png)

Currently the zaakvertrouwelijkheidaanduiding is actually patched and not the document itself. Please use: https://zac-test.utrechtproeftuin.nl/api/docs/#operation/core_cases_document_partial_update

**Comment by svenvandescheur** [comment]
https://github.com/GemeenteUtrecht/zaakafhandelcomponent/pull/529
