### ISSUE TITLE
Add a landing page with a pick of Regiezaken

### ISSUE THREAD

**Issue by sergei-maertens** [GemeenteUtrecht/zaakafhandelcomponent#7]
In #6 (requirement for this ticket) - it's possible to define logical clusters of Zaken.

In the UI, this needs to be presented for end users:

* create landing page with all the regietypes displayed with their label
* page should be login-protected
* each regietype should link to a deeper page where cases of the main zaaktype are listed

You can (re-use) the blue blocks as in the BInG application (landing page).

**Comment by annashamray** [comment]
Implemented in https://github.com/GemeenteUtrecht/zaakafhandelcomponent/pull/12
